spring:
  application:
    name: OrderDemo

  datasource:
    url: jdbc:mysql://localhost:3306/orderService
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-2d8txn41w8quqhi6.us.auth0.com/
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: email
            client-id: peW6OFHBYfVcaid1ARPaNQPiItNdJnbm
            client-secret: PAG4jkvfqOe3uDNMIIEEDAW2IOYyoUohhYParNZaGFwHtlHBauIcp65gotWVq_42
        provider:
          okta:
            issuer-uri: https://dev-2d8txn41w8quqhi6.us.auth0.com/

server:
  port: 9093
  ssl:
    enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:9095/eureka}
    register-with-eureka: true
    fetch-registry: true
